// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(VIPServicesRudyTestContext))]
    partial class VIPServicesRudyTestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainLibrary.Domain.Client.Category", b =>
                {
                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DomainLibrary.Domain.Client.Client", b =>
                {
                    b.Property<int>("ClientNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ClientNumber");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DomainLibrary.Domain.Limousines.Limousine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastReservation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Limousines");
                });

            modelBuilder.Entity("DomainLibrary.Domain.Reservering.Reservation", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientNumber")
                        .HasColumnType("int");

                    b.HasKey("Number");

                    b.HasIndex("ClientNumber");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DomainLibrary.Domain.Reservering.Reservation", b =>
                {
                    b.HasOne("DomainLibrary.Domain.Client.Client", null)
                        .WithMany("Reservations")
                        .HasForeignKey("ClientNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
